### ISSUE TITLE
pip

### ISSUE THREAD

**Issue by xloem** [berdav/qemu-rpi-gpio#1]
Hey, how are things going?

I notice in your README you said a push to pip was imminent.  I'm inferring that ran into snags.  Any update?

**Comment by berdav** [comment]
Hi, thank you for your interest in this project!

I had temporary parked this project some times ago, I think it's time to refine it. :)

I've pushed the package to pypi, you can find it at https://pypi.org/project/qemu-rpi-gpio/ and install it using
```
pip install qemu-rpi-gpio
```

I'm closing the issue for now, if the python package has some problems let me know opening a new issue.

Thank you!

**Comment by xloem** [comment]
Thanks for addressing this so rapidly.  I ended up setting up a real pi to run my tests, but I'll likely by trying the pip package at some point in the future.
